version: '3'
    
services:
  web_django:
    build: .
    command: python /code/resuelve/manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=False
      - ALLOWED_HOST=localhost
    volumes:
      - .:/code
    ports:
      - "8000:8000"
